# This is a basic workflow to help you get started with Actions
name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
    - name: jst exec ls
      run: pwd && ls `pwd` && echo "done"
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Debug APK
      run: bash ./gradlew :app:assembleFdroidDebug
      
    - name: show result apks
      run: ls `pwd` && echo "ls2 done" && pwd && echo "search deeper----" && ls /home/runner/work/Goodtime/Goodtime/app/build/outputs/ && echo "search deeper done" && cd /home/runner/work/Goodtime/Goodtime/app/build/outputs/ &&echo "ls -R" && ls -R |awk '{print i$0}' i=`pwd`'/' && echo "ls -R and awk done!!"
#/home/runner/work/Goodtime/Goodtime/app/src/main/java/com/apps/adrcotfas/goodtime/Session.java:34: w
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: App
        path: /home/runner/work/Goodtime/Goodtime/app/build/outputs/apk/fdroid/deubg/app-fdroid-debug.apk
